# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/trim_reads.smk"
include: "rules/hybpiper.smk"
include: "rules/align.smk"
include: "rules/trim_alignments.smk"
include: "rules/gene_trees.smk"
include: "rules/species_tree.smk"

# workdir: config['outdir']

rule all:
    input:
        "astral/astral4.tre",
        "astral/wastral.tre",
        "astral/astral_4_bs10_scored.tre",
        "astral/astral_4_bs10_poly.tre",
        "astral/astral_4_bs10_qs.tre",
        "astral/astral_4_bs10_qf.tre"
