samples: /home/eab77806/hybpiper_astral_pipeline/config/samples.tsv

outdir: /scratch/eab77806/hybpiper_snakemake

# include either -t_aa for an amino acid target file or -t_dna for a dna target file
target_file_command: "-t_dna target/combined.target_problem_genes_removed.fa"

# for dna target files, include --bwa
hybpiper_extra_flags: "--bwa --timeout_exonerate_contigs 3000 --cov_cutoff 3 "

# whether you want to retrieve genes or supercontigs. accepted values: gene, GENE, supercontig, SUPERCONTIG
sequence_type: supercontig

# name of outgroup tip in tree
outgroup: darlingtonia_californica_SRR24877818
